#!/usr/bin/env bash
xhost +local:
sudo systemd-nspawn --setenv=DISPLAY=:0 -b -D /debian/ -M debian --bind-ro=/tmp/.X11-unix --bind=/dev/dri --bind=/dev/shm --bind=/dev/snd --bind=/run/user/1000/pulse:/run/user/host/pulse
