esphome:
  name: fireplace
  platform: ESP32
  board: nodemcu-32s

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
  password: "5b9230d079c34c91e9290d9cb1526f71"

wifi:
  ssid: "redgroup"
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Fireplace Fallback Hotspot"
    password: "Ehn1uMmcFx82"

captive_portal:

sensor:
  - platform: dht
    pin: GPIO23
    model: DHT22_TYPE2
    temperature:
      name: "fireplace temperature"
    humidity:
      name: "fireplace humidity"
    update_interval: 60s